CREATE TABLE "GCG_5592_INSP_HIST"(
 "RUNID" BIGINT,
 "PURCHASE_ORDER" CHAR(7),
 "PO_LINE" CHAR(4),
 "RECEIVER_NO" CHAR(6) );
CREATE INDEX "IND1" USING 0 IN DICTIONARY  ON "GCG_5592_INSP_HIST" ( "RUNID", "PURCHASE_ORDER", "PO_LINE" );